import type { LaneMeta, MidiEvent, Pattern } from './types.js';
import { euclid, lcm } from './groove-math.ts';
// Engine ground truth. Regenerated by scripts/generate-presets-json.mjs during
// site prebuild. Hand edits are overwritten — fix the C++ preset factory or the
// emitter instead.
import presetsRaw from '../generated/presets.json' with { type: 'json' };

// Emitter contract — see engine/tools/emit_presets.cpp for the writer side.
interface JsonLane {
  laneIndex: number;
  noteNumber: number;
  roleLabel: string;
  role: string;
  cycleSteps: number;
  subdivision: number;
  stepLen: number;
  hits: number;
  rotation: number;
  velocity: number;
  probability: number;
}
interface JsonPreset {
  index: number;
  name: string;
  description: string;
  activeLaneCount: number;
  notesInBar: number;
  seed: number;
  lanes: JsonLane[];
}
interface JsonSchema {
  schemaVersion: number;
  presetCount: number;
  presets: JsonPreset[];
}

const PRESETS = presetsRaw as JsonSchema;
const PRESETS_BY_ENGINE_NAME = new Map<string, JsonPreset>(
  PRESETS.presets.map((p) => [p.name, p]),
);

const TICKS_PER_BEAT = 4;
const TICKS_PER_BAR = TICKS_PER_BEAT * 4;
const MAX_DRIFT_BARS = 256;

// Card-preview aesthetic. Not part of engine ground truth — the plugin's BPM
// is host-transport driven. These BPMs are what the site card runtime plays
// at; a preset missing from this table falls back to 120.
const PRESET_BPM: Record<string, number> = {
  'Four on the Floor': 120,
  'Polymetric Drift': 110,
  'Sparse Pulse': 90,
  Breakbeat: 140,
  'Latin Feel': 100,
  'Afro-House Phrases': 122,
  'Reich Phasing': 108,
  'Kotekan Interlock': 120,
  'Pocket Groove': 92,
  'Afrobeat 12/8': 96,
  'Balkan Aksak': 140,
  'Bossa Nova': 130,
  'Carnatic Tala': 100,
  'IDM Glitch': 100,
  'Reich Phase Process': 100,
};

// Card-preview drift accelerator. Engine reaches full phase over ~2 minutes via
// scene macros; the card doubles the drift rate so the six-phase relationship
// is audible in a short listen. Card-only override — the plugin path plays
// engine-faithful drift. Keys are engine preset names; values map lane index →
// drift steps/bar.
const DRIFT_OVERRIDES: Record<string, Record<number, number>> = {
  'Reich Phase Process': { 1: 2 },
};

// Role → card lane color. Falls back to the 'perc' hue for unmapped roles.
const HUE: Record<string, string> = {
  kick: '#e07a3f',
  snare: '#d3a12b',
  rim: '#d3a12b',
  hat: '#7fb37a',
  openhat: '#7fb37a',
  clap: '#6a5c8c',
  ghost: '#6a5c8c',
  tom: '#8fb0d6',
  conga: '#8fb0d6',
  bongo: '#8fb0d6',
  timbale: '#8fb0d6',
  cowbell: '#c4915d',
  woodblock: '#c4915d',
  agogo: '#c4915d',
  clave: '#e0c26e',
  triangle: '#e0c26e',
  shaker: '#7fb37a',
  guiro: '#7fb37a',
  cymbal: '#7fb37a',
  cuica: '#8fb0d6',
  perc: '#8fb0d6',
};

// roleLabel → human-readable lane label. Any unknown role falls through to
// capitalize().
const LABEL_FROM_ROLE_LABEL: Record<string, string> = {
  kick: 'Kick',
  snare: 'Snare',
  rim: 'Rim',
  hat: 'Hi-hat',
  openhat: 'Open hat',
  clap: 'Clap',
  ghost: 'Ghost',
  tom: 'Tom',
  conga: 'Conga',
  bongo: 'Bongo',
  timbale: 'Timbale',
  cowbell: 'Cowbell',
  woodblock: 'Woodblock',
  agogo: 'Agogo',
  clave: 'Clave',
  triangle: 'Triangle',
  shaker: 'Shaker',
  guiro: 'Guiro',
  cymbal: 'Cymbal',
  cuica: 'Cuica',
  perc: 'Perc',
};

// Engine Role enum values that describe a lane's *function* better than its
// instrument. When the emitter reports one of these, the card labels the lane
// with the function name — otherwise it uses the instrument (roleLabel).
const FUNCTIONAL_ROLE_LABELS: Record<string, string> = {
  Ghost: 'Ghost',
  Fill: 'Fill',
  Ornament: 'Ornament',
  Accent: 'Accent',
};

// Display names accepted by the card. Everything here must correspond to a real
// engine preset name after stripping any 'Factory: ' prefix. Kept as a curated
// set so we can (a) reject typos in chapter MDX files, and (b) return them from
// listPresetNames() for the existing site test suite. T04 audits the CHAPTER_
// ALIASES table against this list.
const FACTORY_DISPLAY_NAMES = [
  'Factory: Four on the Floor',
  'Factory: Polymetric Drift',
  'Factory: Sparse Pulse',
  'Factory: Breakbeat',
  'Factory: Latin Feel',
  'Factory: Afro-House Phrases',
  'Factory: Reich Phasing',
  'Factory: Kotekan Interlock',
  'Factory: Pocket Groove',
  'Factory: Afrobeat 12/8',
  'Factory: Balkan Aksak',
  'Factory: Bossa Nova',
  'Factory: Carnatic Tala',
  'Factory: IDM Glitch',
] as const;

const BARE_DISPLAY_NAMES = ['Reich Phase Process'] as const;

const DISPLAY_NAMES: string[] = [...BARE_DISPLAY_NAMES, ...FACTORY_DISPLAY_NAMES];
const DISPLAY_NAME_SET = new Set<string>(DISPLAY_NAMES);

// Chapter cards use display-friendly names ('Jungle Break', 'Cuban Son
// Montuno', ...). Each entry maps a chapter card's preset= value to a factory
// display name. Preserved verbatim from the pre-T02 map; T04 audits every
// entry against the engine ground truth and fixes drift.
const CHAPTER_ALIASES: Record<string, string> = {
  'Polymetric Foundation': 'Factory: Polymetric Drift',
  'Ewe Polymetric Ensemble': 'Factory: Afrobeat 12/8',
  'Manding Djembe': 'Factory: Afrobeat 12/8',
  'Cuban Son Montuno': 'Factory: Latin Feel',
  'Afrobeat Lagos': 'Factory: Afrobeat 12/8',
  'Balinese Kotekan': 'Factory: Kotekan Interlock',
  'Javanese Colotomic': 'Factory: Kotekan Interlock',
  'Rupak Tal': 'Factory: Balkan Aksak',
  'Tintal Groove': 'Factory: Carnatic Tala',
  'Kopanitsa 11/8': 'Factory: Balkan Aksak',
  'Rachenitsa 7/8': 'Factory: Balkan Aksak',
  'Nancarrow Tempi': 'Factory: Polymetric Drift',
  'Riley Layered Entry': 'Factory: Afro-House Phrases',
  'Deep House': 'Factory: Four on the Floor',
  'Minimal Techno': 'Factory: Four on the Floor',
  'Bossa Nova Trio': 'Factory: Bossa Nova',
  'Samba Batucada': 'Factory: Bossa Nova',
  'Classic Funk': 'Factory: Pocket Groove',
  'Neo-Soul Pocket': 'Factory: Pocket Groove',
  'Elvin Jones Cascade': 'Factory: Polymetric Drift',
  'Jazz Bop Ride': 'Factory: Pocket Groove',
  'Jungle Break': 'Factory: Breakbeat',
  'Liquid Drum and Bass': 'Factory: Breakbeat',
  'Afro-Electronic Fusion': 'Factory: Afro-House Phrases',
  'Balkan Funk': 'Factory: Balkan Aksak',
  'Compositional Arc': 'Factory: Afro-House Phrases',
};

// --- Rendering primitives (unchanged shape; now fed by JSON) ---

interface LaneSpec {
  label: string;
  role: string;
  color: string;
  note: number;
  steps: number;
  stepLen: number;
  hits: number;
  velocity: number;
  rot: number;
  driftStepsPerBar: number;
}

interface PatternSpec {
  bpm: number;
  lanes: LaneSpec[];
}

// Smallest positive N such that floor(N * |drift|) is a positive multiple of
// steps — how many 4-beat bars drift needs to return a lane to its start.
function driftPeriodBars(steps: number, drift: number): number {
  if (drift === 0) return 1;
  const abs = Math.abs(drift);
  for (let n = 1; n <= MAX_DRIFT_BARS; n++) {
    const shift = Math.floor(n * abs);
    if (shift > 0 && shift % steps === 0) return n;
  }
  return MAX_DRIFT_BARS;
}

function laneEvents(
  laneIdx: number,
  lane: LaneSpec,
  totalTicks: number,
): MidiEvent[] {
  const hitsArr = euclid(lane.hits, lane.steps);
  const staticRot = lane.rot;
  const drift = lane.driftStepsPerBar;
  const steps = lane.steps;
  const events: MidiEvent[] = [];
  for (let tick = 0; tick < totalTicks; tick += lane.stepLen) {
    const rawStep = (tick / lane.stepLen) % steps;
    const driftSteps =
      drift === 0 ? 0 : Math.floor((tick / TICKS_PER_BAR) * drift);
    const idx = (((rawStep + staticRot + driftSteps) % steps) + steps) % steps;
    if (hitsArr[idx]) {
      events.push({
        beat: tick / TICKS_PER_BEAT,
        note: lane.note,
        velocity: lane.velocity,
        lane: laneIdx,
      });
    }
  }
  return events;
}

function toLaneMeta(specs: LaneSpec[]): LaneMeta[] {
  return specs.map((l) => ({
    label: l.label,
    role: l.role,
    note: l.note,
    color: l.color,
  }));
}

function buildPattern(spec: PatternSpec): Pattern {
  const baseCompositeTicks = spec.lanes.reduce(
    (acc, l) => lcm(acc, l.steps * l.stepLen),
    1,
  );
  const driftCompositeTicks = spec.lanes.reduce((acc, l) => {
    if (l.driftStepsPerBar === 0) return acc;
    return lcm(acc, driftPeriodBars(l.steps, l.driftStepsPerBar) * TICKS_PER_BAR);
  }, 1);
  const totalTicks = lcm(baseCompositeTicks, driftCompositeTicks);
  const events = spec.lanes
    .flatMap((l, i) => laneEvents(i, l, totalTicks))
    .sort((a, b) => a.beat - b.beat);
  return {
    bpm: spec.bpm,
    loopBeats: totalTicks / TICKS_PER_BEAT,
    events,
    lanes: toLaneMeta(spec.lanes),
  };
}

// --- JSON → LaneSpec conversion ---

function capitalize(s: string): string {
  return s.length ? s[0].toUpperCase() + s.slice(1) : s;
}

function laneLabel(
  role: string,
  roleLabel: string,
  priorLabels: string[],
): string {
  const functional = FUNCTIONAL_ROLE_LABELS[role];
  const base =
    functional ?? LABEL_FROM_ROLE_LABEL[roleLabel] ?? capitalize(roleLabel);
  // Disambiguate duplicate labels within a single preset so two identical
  // pattern-A/pattern-B lanes read cleanly.
  const priorCount = priorLabels.filter((l) => l === base).length;
  return priorCount === 0 ? base : `${base} ${priorCount + 1}`;
}

function jsonLaneToSpec(
  lane: JsonLane,
  drift: number | undefined,
  priorLabels: string[],
): LaneSpec {
  return {
    label: laneLabel(lane.role, lane.roleLabel, priorLabels),
    role: lane.roleLabel,
    color: HUE[lane.roleLabel] ?? HUE.perc,
    note: lane.noteNumber,
    steps: lane.cycleSteps,
    stepLen: lane.stepLen,
    hits: lane.hits,
    velocity: lane.velocity,
    rot: lane.rotation,
    driftStepsPerBar: drift ?? 0,
  };
}

function jsonPresetToSpec(preset: JsonPreset, engineName: string): PatternSpec {
  const drifts = DRIFT_OVERRIDES[engineName];
  const specs: LaneSpec[] = [];
  const priorLabels: string[] = [];
  preset.lanes.forEach((lane, idx) => {
    const spec = jsonLaneToSpec(lane, drifts?.[idx], priorLabels);
    priorLabels.push(spec.label);
    specs.push(spec);
  });
  return {
    bpm: PRESET_BPM[engineName] ?? 120,
    lanes: specs,
  };
}

// --- Resolution ---

// A display name that starts with 'Factory: ' resolves to its bare engine
// counterpart; otherwise the display name IS the engine name.
function engineNameFor(displayName: string): string | null {
  if (PRESETS_BY_ENGINE_NAME.has(displayName)) return displayName;
  const prefix = 'Factory: ';
  if (displayName.startsWith(prefix)) {
    const bare = displayName.slice(prefix.length);
    if (PRESETS_BY_ENGINE_NAME.has(bare)) return bare;
  }
  return null;
}

export interface ResolvedPreset {
  engineName: string;
  displayName: string;
  notesInBar: number;
  bpm: number;
  lanes: LaneMeta[];
}

// Look up a chapter/factory name and return the engine-resolved preset. Used
// by the card runtime and the (upcoming) preset-consistency Playwright gate to
// prove card ↔ WASM-host agreement on lane structure per chapter.
export function resolvePreset(name: string): ResolvedPreset | null {
  const displayName = resolvePresetName(name);
  if (!displayName) return null;
  const engineName = engineNameFor(displayName);
  if (!engineName) return null;
  const preset = PRESETS_BY_ENGINE_NAME.get(engineName);
  if (!preset) return null;
  const spec = jsonPresetToSpec(preset, engineName);
  return {
    engineName,
    displayName,
    notesInBar: preset.notesInBar,
    bpm: spec.bpm,
    lanes: toLaneMeta(spec.lanes),
  };
}

export function getPatternForPreset(name: string): Pattern | null {
  const displayName = resolvePresetName(name);
  if (!displayName) return null;
  const engineName = engineNameFor(displayName);
  if (!engineName) return null;
  const preset = PRESETS_BY_ENGINE_NAME.get(engineName);
  if (!preset) return null;
  return buildPattern(jsonPresetToSpec(preset, engineName));
}

// Resolve a name into its canonical display name (with 'Factory: ' preserved
// when the input goes through the alias map). Returns null when the name is
// neither a known display name nor a chapter alias.
export function resolvePresetName(name: string): string | null {
  if (DISPLAY_NAME_SET.has(name)) return name;
  const aliased = CHAPTER_ALIASES[name];
  if (aliased && DISPLAY_NAME_SET.has(aliased)) return aliased;
  return null;
}

export function listPresetNames(): string[] {
  return [...DISPLAY_NAMES];
}

export function listChapterAliases(): string[] {
  return Object.keys(CHAPTER_ALIASES);
}
