import type { LaneMeta } from './types.js';
// Engine ground truth. Regenerated by scripts/generate-presets-json.mjs during
// site prebuild. Hand edits are overwritten — fix the C++ preset factory or the
// emitter instead.
import presetsRaw from '../generated/presets.json' with { type: 'json' };

// Emitter contract — see engine/tools/emit_presets.cpp for the writer side.
interface JsonLane {
  laneIndex: number;
  noteNumber: number;
  roleLabel: string;
  role: string;
  cycleSteps: number;
  subdivision: number;
  stepLen: number;
  hits: number;
  rotation: number;
  velocity: number;
  probability: number;
}
interface JsonPreset {
  index: number;
  name: string;
  description: string;
  activeLaneCount: number;
  notesInBar: number;
  seed: number;
  lanes: JsonLane[];
}
interface JsonSchema {
  schemaVersion: number;
  presetCount: number;
  presets: JsonPreset[];
}

const PRESETS = presetsRaw as JsonSchema;
const PRESETS_BY_ENGINE_NAME = new Map<string, JsonPreset>(
  PRESETS.presets.map((p) => [p.name, p]),
);

// Card-preview aesthetic. Not part of engine ground truth — the plugin's BPM
// is host-transport driven. These BPMs are what the site card runtime plays
// at; a preset missing from this table falls back to 120.
const PRESET_BPM: Record<string, number> = {
  'Four on the Floor': 120,
  'Polymetric Drift': 110,
  'Sparse Pulse': 90,
  Breakbeat: 140,
  'Latin Feel': 100,
  'Afro-House Phrases': 122,
  'Reich Phasing': 108,
  'Kotekan Interlock': 120,
  'Pocket Groove': 92,
  'Afrobeat 12/8': 96,
  'Balkan Aksak': 140,
  'Kopanitsa 11/8': 200,
  'Bossa Nova': 130,
  'Bossa Nova Trio': 130,
  'Carnatic Tala': 100,
  'IDM Glitch': 100,
  'Reich Phase Process': 100,
  'Jungle Break': 140,
};

// Role → card lane color. Falls back to the 'perc' hue for unmapped roles.
const HUE: Record<string, string> = {
  kick: '#e07a3f',
  snare: '#d3a12b',
  rim: '#d3a12b',
  hat: '#7fb37a',
  openhat: '#7fb37a',
  clap: '#6a5c8c',
  ghost: '#6a5c8c',
  tom: '#8fb0d6',
  conga: '#8fb0d6',
  bongo: '#8fb0d6',
  timbale: '#8fb0d6',
  cowbell: '#c4915d',
  woodblock: '#c4915d',
  agogo: '#c4915d',
  clave: '#e0c26e',
  triangle: '#e0c26e',
  shaker: '#7fb37a',
  guiro: '#7fb37a',
  cymbal: '#7fb37a',
  cuica: '#8fb0d6',
  perc: '#8fb0d6',
};

// roleLabel → human-readable lane label. Any unknown role falls through to
// capitalize().
const LABEL_FROM_ROLE_LABEL: Record<string, string> = {
  kick: 'Kick',
  snare: 'Snare',
  rim: 'Rim',
  hat: 'Hi-hat',
  openhat: 'Open hat',
  clap: 'Clap',
  ghost: 'Ghost',
  tom: 'Tom',
  conga: 'Conga',
  bongo: 'Bongo',
  timbale: 'Timbale',
  cowbell: 'Cowbell',
  woodblock: 'Woodblock',
  agogo: 'Agogo',
  clave: 'Clave',
  triangle: 'Triangle',
  shaker: 'Shaker',
  guiro: 'Guiro',
  cymbal: 'Cymbal',
  cuica: 'Cuica',
  perc: 'Perc',
};

// Engine Role enum values that describe a lane's *function* better than its
// instrument. When the emitter reports one of these, the card labels the lane
// with the function name — otherwise it uses the instrument (roleLabel).
const FUNCTIONAL_ROLE_LABELS: Record<string, string> = {
  Ghost: 'Ghost',
  Fill: 'Fill',
  Ornament: 'Ornament',
  Accent: 'Accent',
};

// Card fallback for chapter presets whose native engine preset references MIDI
// notes not yet in site/public/samples/manifest.json. Without a redirect these
// cards would trip the fail-loud scheduler on missing samples. Each key IS a
// real engine preset — the alias exists purely to substitute a manifest-safe
// pattern until sample coverage catches up. Uncovered notes are noted per row
// so a future manifest extension can retire the alias.
// M043 S11 T05 widened manifest to cover 44/47/48/62/72 via close-pitch reuse.
// T06 sourced genuine samples for ride (51), china-as-splash-fallback (55),
// low conga (64), and long guiro (74) — Muldjord ride/china, FreePats LowConga,
// VCSL Guiro_Slow. All 7 remaining aliases (Balinese Kotekan, Javanese
// Colotomic, Bossa Nova Trio, Elvin Jones Cascade, Jazz Bop Ride, Liquid Drum
// and Bass, Afro-Electronic Fusion) are now retired — every chapter preset
// resolves to its native engine preset.
const CHAPTER_ALIASES: Record<string, string> = {};

// --- JSON → LaneMeta conversion ---

function capitalize(s: string): string {
  return s.length ? s[0].toUpperCase() + s.slice(1) : s;
}

function laneLabel(
  role: string,
  roleLabel: string,
  priorLabels: string[],
): string {
  const functional = FUNCTIONAL_ROLE_LABELS[role];
  const base =
    functional ?? LABEL_FROM_ROLE_LABEL[roleLabel] ?? capitalize(roleLabel);
  // Disambiguate duplicate labels within a single preset so two identical
  // pattern-A/pattern-B lanes read cleanly.
  const priorCount = priorLabels.filter((l) => l === base).length;
  return priorCount === 0 ? base : `${base} ${priorCount + 1}`;
}

function jsonPresetToLaneMeta(preset: JsonPreset): LaneMeta[] {
  const specs: LaneMeta[] = [];
  const priorLabels: string[] = [];
  for (const lane of preset.lanes) {
    const label = laneLabel(lane.role, lane.roleLabel, priorLabels);
    priorLabels.push(label);
    specs.push({
      label,
      role: lane.roleLabel,
      note: lane.noteNumber,
      color: HUE[lane.roleLabel] ?? HUE.perc,
    });
  }
  return specs;
}

// --- Resolution ---

// A display name that starts with 'Factory: ' resolves to its bare engine
// counterpart; otherwise the display name IS the engine name.
function engineNameFor(displayName: string): string | null {
  if (PRESETS_BY_ENGINE_NAME.has(displayName)) return displayName;
  const prefix = 'Factory: ';
  if (displayName.startsWith(prefix)) {
    const bare = displayName.slice(prefix.length);
    if (PRESETS_BY_ENGINE_NAME.has(bare)) return bare;
  }
  return null;
}

export interface ResolvedPreset {
  engineName: string;
  displayName: string;
  notesInBar: number;
  bpm: number;
  lanes: LaneMeta[];
  // Emitter-assigned engine index — used by the card runtime to feed
  // _poly_load_preset(ctx, index). Kept alongside engineName so the WASM
  // scheduler and dump paths never re-derive it from a name lookup.
  index: number;
  // Per-lane roleLabel + role strings copied from presets.json. The engine
  // exposes neither via _poly_lane_int/float, so we pass them into
  // buildEngineParams() to keep the params.json snapshot self-describing.
  laneRoleMeta: Array<{ roleLabel: string; role: string }>;
}

// Look up a chapter/factory name and return the engine-resolved preset. Used
// by the card runtime and the preset-consistency Playwright gate to prove
// card ↔ WASM-host agreement on lane structure per chapter.
export function resolvePreset(name: string): ResolvedPreset | null {
  const displayName = resolvePresetName(name);
  if (!displayName) return null;
  const engineName = engineNameFor(displayName);
  if (!engineName) return null;
  const preset = PRESETS_BY_ENGINE_NAME.get(engineName);
  if (!preset) return null;
  return {
    engineName,
    displayName,
    notesInBar: preset.notesInBar,
    bpm: PRESET_BPM[engineName] ?? 120,
    lanes: jsonPresetToLaneMeta(preset),
    index: preset.index,
    laneRoleMeta: preset.lanes.map((l) => ({
      roleLabel: l.roleLabel,
      role: l.role,
    })),
  };
}

// Resolve a name into its canonical display name. Aliases run first so a
// chapter can be redirected to a manifest-safe fallback even when its own
// engine preset exists. Otherwise any real engine name (bare or 'Factory: '
// prefixed) resolves to itself. Returns null when the name is neither a
// known engine preset nor a chapter alias.
export function resolvePresetName(name: string): string | null {
  const aliased = CHAPTER_ALIASES[name];
  if (aliased) return engineNameFor(aliased) ? aliased : null;
  return engineNameFor(name) ? name : null;
}

// All engine preset names, in emitter order.
export function listPresetNames(): string[] {
  return PRESETS.presets.map((p) => p.name);
}

export function listChapterAliases(): string[] {
  return Object.keys(CHAPTER_ALIASES);
}
