# =============================================================================
# jk_embed_assets.cmake — embed files as C arrays at configure time
# Canonical use: web UI bundle (webui/*) -> poly_webui_assets.h so the
# plugin binary is self-contained (no filesystem or remote content).
#
#   jk_embed_assets(<out_header> <namespace> <file1> [file2 ...])
#
# Generates <out_header> with, per file:
#   inline const unsigned char k_<ident>[] = { ... };
# plus an Asset table and lookup(path) helper. Paths are the basenames
# prefixed with '/'.
# =============================================================================
function(jk_embed_assets out_header ns)
    set(body "// Generated by jk_embed_assets.cmake — do not edit.\n")
    string(APPEND body "#pragma once\n#include <cstddef>\n#include <string_view>\n\n")
    string(APPEND body "namespace ${ns} {\n\n")
    string(APPEND body "struct Asset { std::string_view path; const unsigned char* data; size_t size; std::string_view mime; };\n\n")

    set(table "")
    foreach(file ${ARGN})
        get_filename_component(base ${file} NAME)
        string(MAKE_C_IDENTIFIER ${base} ident)
        file(READ ${file} hex HEX)
        string(REGEX REPLACE "(..)" "0x\\1," bytes ${hex})
        string(APPEND body "inline const unsigned char k_${ident}[] = { ${bytes} };\n")

        if(base MATCHES "\\.html$")
            set(mime "text/html")
        elseif(base MATCHES "\\.js$")
            set(mime "text/javascript")
        elseif(base MATCHES "\\.css$")
            set(mime "text/css")
        else()
            set(mime "application/octet-stream")
        endif()
        string(APPEND table "    { \"/${base}\", k_${ident}, sizeof(k_${ident}), \"${mime}\" },\n")
    endforeach()

    string(APPEND body "\ninline const Asset kAssets[] = {\n${table}};\n\n")
    string(APPEND body "inline const Asset* lookup(std::string_view path) {\n")
    string(APPEND body "    for (const auto& a : kAssets)\n        if (a.path == path)\n            return &a;\n")
    string(APPEND body "    return nullptr;\n}\n\n} // namespace ${ns}\n")

    file(WRITE ${out_header} "${body}")

    # Re-run configure when any source file changes so the header is regenerated.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${ARGN})
endfunction()
